export * from './actions';

export const CONSTANTS = {
    LOG_IN: "LOG_IN",
    IS_AUTH: "IS_AUTH",
    IS_ONLINE: "IS_ONLINE",
    GET_MESSAGES: "GET_MESSAGES",
    START_SOCKET: "START_SOCKET",
    SEND_MESSAGE:"SEND_MESSAGE",
    NOTIFY:"NOTIFY",
    CLOSE_SOCKET:"CLOSE_SOCKET",
    RESET_SOCKET:"RESET_SOCKET"
}